created: 2026-06-11T08:00:50.074Z
updated: 2026-06-11T08:00:54.445Z
update_count: 2
last_field: diagram
kind: nested-class
title: workspace-ui
children:
  - connections-view
  - control-server
  - inspector
  - library-center
  - settings
  - workspace-model
parentPath: []
